-- Giftmap · 데모 데이터 seed
-- 자동 생성 파일입니다. 직접 고치지 말고 아래 명령으로 다시 만드세요.
--   dart run tool/generate_supabase_seed.dart
--
-- 실행 순서: migrations/0001_init_schema.sql 을 먼저 실행한 뒤 이 파일을 실행합니다.
-- 모든 상품은 is_demo = true 입니다. 실제 판매 상품이 아닙니다.

begin;

-- categories ------------------------------------------------
insert into public.categories (id, label, group_id, group_label, sort_order) values
  ('beauty', '뷰티', 'beauty_care', '뷰티·케어', 1),
  ('body_care', '바디케어', 'beauty_care', '뷰티·케어', 2),
  ('candle', '캔들·디퓨저', 'home_living', '홈·리빙', 3),
  ('desk', '데스크 액세서리', 'desk_stationery', '문구·데스크', 4),
  ('dessert', '디저트', 'food_drink', '푸드·디저트', 5),
  ('fashion_accessory', '패션 액세서리', 'fashion', '패션·잡화', 6),
  ('hand_care', '핸드케어', 'beauty_care', '뷰티·케어', 7),
  ('hobby', '취미·소품', 'hobby', '취미·라이프스타일', 8),
  ('homewear', '홈웨어', 'home_living', '홈·리빙', 9),
  ('living', '생활용품', 'home_living', '홈·리빙', 10),
  ('perfume', '향수', 'beauty_care', '뷰티·케어', 11),
  ('stationery', '문구', 'desk_stationery', '문구·데스크', 12),
  ('tea_coffee', '차·커피', 'food_drink', '푸드·디저트', 13),
  ('tumbler', '텀블러', 'home_living', '홈·리빙', 14),
  ('wallet', '지갑·카드지갑', 'fashion', '패션·잡화', 15)
on conflict (id) do update set
  label = excluded.label,
  group_id = excluded.group_id,
  group_label = excluded.group_label,
  sort_order = excluded.sort_order,
  is_active = true;

-- products --------------------------------------------------
insert into public.products (
  id, brand_name, product_name, category_id, sub_category,
  price, original_price, discount_rate, image_asset, product_url,
  tags, occasions, recipient_types, gender_target, age_range,
  price_range, recommendation_keywords, description,
  recommendation_reason, is_demo, sort_order
) values
  ('perfume_01', '무드셀렉트', '데이브레이크 오 드 뚜왈렛 50ml', 'perfume', '오 드 뚜왈렛',
   68000, 86000, 21, null, null,
   '{"scent","beauty"}', '{"birthday","anniversary"}', '{"partner","friend"}', null, '{"twenties","thirties"}',
   'from50kTo100k', '{"향수","오드뚜왈렛","생일 향수 선물"}', '이른 아침의 공기를 닮은 시트러스 우디 향. 가볍게 뿌려도 잔향이 오래 남습니다.',
   '향이 과하지 않아 선물로 부담이 적어요.', true, 1),
  ('perfume_02', '센트그램', '포레스트 미니 퍼퓸 세트 3종', 'perfume', '미니 세트',
   42000, null, null, null, null,
   '{"scent","beauty"}', '{"birthday","thanks","holiday"}', '{"friend","colleague","acquaintance"}', null, '{"twenties","thirties"}',
   'from30kTo50k', '{"미니 향수 세트","향수 선물세트"}', '숲, 코튼, 시트러스 세 가지 향을 10ml씩 담은 미니 세트입니다.',
   '취향을 모를 때 여러 향을 함께 고를 수 있어요.', true, 2),
  ('perfume_03', '온도', '페어 앤 머스크 헤어 미스트', 'perfume', '헤어 미스트',
   29000, 34000, 15, null, null,
   '{"scent","beauty"}', '{"birthday","support","thanks"}', '{"friend","colleague"}', null, '{"teens","twenties"}',
   'from10kTo30k', '{"헤어미스트","가벼운 향 선물"}', '머리카락에 가볍게 뿌리는 저자극 헤어 미스트. 배 향과 화이트 머스크가 섞여 있습니다.',
   '향수보다 가벼워 첫 선물로 좋아요.', true, 3),
  ('hand_care_01', '데일리핏', '시어버터 핸드크림 3종 기프트', 'hand_care', '핸드크림',
   32000, 38000, 16, null, null,
   '{"scent","beauty"}', '{"thanks","holiday","birthday","support"}', '{"colleague","friend","acquaintance"}', null, '{"twenties","thirties","fortiesPlus"}',
   'from30kTo50k', '{"핸드크림 선물세트","무향 핸드크림"}', '끈적임이 적은 시어버터 핸드크림 50ml 3종 구성입니다.',
   '가격 부담이 작으면서 챙긴 느낌이 확실해요.', true, 4),
  ('hand_care_02', '온도', '무향 핸드 앤 네일 밸런스', 'hand_care', '핸드크림',
   18000, null, null, null, null,
   '{"beauty"}', '{"thanks","support","holiday"}', '{"colleague","manager","acquaintance"}', null, '{"thirties","fortiesPlus"}',
   'from10kTo30k', '{"무향 핸드크림","사무실 선물"}', '향을 넣지 않은 손·손톱 겸용 밤. 사무 공간에서도 부담이 없습니다.',
   '향 취향을 몰라도 안전한 선택이에요.', true, 5),
  ('hand_care_03', '소소한하루', '핸드워시 & 핸드크림 듀오', 'hand_care', '세트',
   26000, null, null, null, null,
   '{"scent","home"}', '{"housewarming","thanks"}', '{"family","friend","acquaintance"}', null, '{"thirties","fortiesPlus"}',
   'from10kTo30k', '{"핸드워시 세트","집들이 선물"}', '세면대에 그대로 두기 좋은 디자인의 핸드워시와 핸드크림 구성입니다.',
   '집들이처럼 공간에 두는 선물로 잘 맞아요.', true, 6),
  ('body_care_01', '코지룸', '라이스 밀크 바디로션 400ml', 'body_care', '바디로션',
   24000, null, null, null, null,
   '{"scent","beauty"}', '{"birthday","thanks","holiday"}', '{"friend","family"}', null, '{"twenties","thirties","fortiesPlus"}',
   'from10kTo30k', '{"바디로션 선물","순한 바디로션"}', '쌀겨 추출물을 담은 순한 바디로션. 펌핑 용기로 매일 쓰기 좋습니다.',
   '매일 쓰는 소모품이라 실패 확률이 낮아요.', true, 7),
  ('body_care_02', '블랑테이블', '배스 솔트 & 스펀지 기프트박스', 'body_care', '입욕',
   39000, 46000, 15, null, null,
   '{"scent","home"}', '{"birthday","support","thanks"}', '{"partner","friend"}', null, '{"twenties","thirties"}',
   'from30kTo50k', '{"입욕제 선물","배스 기프트박스"}', '라벤더와 유칼립투스 배스 솔트, 천연 스펀지를 함께 담았습니다.',
   '쉬어가라는 메시지를 담기 좋아요.', true, 8),
  ('body_care_03', '데일리핏', '릴랙스 바디 오일 200ml', 'body_care', '바디오일',
   34000, null, null, null, null,
   '{"scent","beauty"}', '{"birthday","anniversary"}', '{"partner","friend"}', null, '{"twenties","thirties"}',
   'from30kTo50k', '{"바디오일 선물"}', '샤워 후 물기 있는 몸에 바르는 가벼운 오일. 은은한 우디 향입니다.',
   '일상에서 쓰면서 선물다운 기분이 남아요.', true, 9),
  ('tea_coffee_01', '리프앤빈', '허브티 12종 테이스팅 박스', 'tea_coffee', '차',
   29000, 35000, 17, null, null,
   '{"food","home"}', '{"thanks","holiday","housewarming","birthday"}', '{"family","manager","colleague","acquaintance"}', null, '{"thirties","fortiesPlus"}',
   'from10kTo30k', '{"허브티 선물세트","차 선물"}', '카페인이 없는 허브티 12종을 한 티백씩 담아 골라 마실 수 있습니다.',
   '연령과 관계를 가리지 않는 무난한 선택이에요.', true, 10),
  ('tea_coffee_02', '리프앤빈', '드립백 커피 20개입 세트', 'tea_coffee', '커피',
   32000, null, null, null, null,
   '{"food"}', '{"thanks","promotion","holiday","support"}', '{"colleague","manager","friend"}', null, '{"twenties","thirties","fortiesPlus"}',
   'from30kTo50k', '{"드립백 선물세트","커피 선물"}', '네 가지 원두를 드립백으로 담아 사무실에서도 간편하게 내릴 수 있습니다.',
   '출근길에 바로 쓰는 선물이라 반응이 좋아요.', true, 11),
  ('tea_coffee_03', '블랑테이블', '티팟 & 찻잔 2인 세트', 'tea_coffee', '티웨어',
   58000, 69000, 16, null, null,
   '{"food","home"}', '{"housewarming","anniversary","holiday"}', '{"family","partner","acquaintance"}', null, '{"thirties","fortiesPlus"}',
   'from50kTo100k', '{"티팟 세트","집들이 티웨어"}', '내열 유리 티팟과 잔 두 개로 구성된 2인용 티웨어입니다.',
   '집들이나 기념일에 무게감 있는 선물이 돼요.', true, 12),
  ('dessert_01', '모먼트', '수제 휘낭시에 10구 박스', 'dessert', '구움과자',
   28000, null, null, null, null,
   '{"food"}', '{"thanks","birthday","support","holiday"}', '{"colleague","friend","acquaintance"}', null, '{"teens","twenties","thirties"}',
   'from10kTo30k', '{"휘낭시에 선물","디저트 선물세트"}', '버터 향이 진한 휘낭시에 10개 구성. 개별 포장되어 나눠 먹기 좋습니다.',
   '여러 사람과 나눌 수 있어 감사 인사에 좋아요.', true, 13),
  ('dessert_02', '모먼트', '다크 초콜릿 어소트 16p', 'dessert', '초콜릿',
   36000, 42000, 14, null, null,
   '{"food"}', '{"anniversary","birthday","thanks"}', '{"partner","friend","colleague"}', null, '{"twenties","thirties","fortiesPlus"}',
   'from30kTo50k', '{"초콜릿 선물","기념일 디저트"}', '카카오 함량이 다른 네 가지 초콜릿을 한 상자에 담았습니다.',
   '기념일에 가볍게 건네기 좋은 구성이에요.', true, 14),
  ('dessert_03', '소소한하루', '말린 과일 & 넛츠 그래놀라', 'dessert', '간식',
   22000, null, null, null, null,
   '{"food"}', '{"thanks","support","housewarming"}', '{"colleague","family","friend"}', null, '{"twenties","thirties"}',
   'from10kTo30k', '{"그래놀라 선물","건강 간식 선물"}', '설탕을 줄인 그래놀라와 건과일을 담은 아침 대용 간식입니다.',
   '부담 없는 가격대에서 챙긴 느낌을 줘요.', true, 15),
  ('candle_01', '센트그램', '우드윅 캔들 200g', 'candle', '캔들',
   38000, 45000, 16, null, null,
   '{"scent","home"}', '{"housewarming","birthday","anniversary"}', '{"partner","friend","family"}', null, '{"twenties","thirties"}',
   'from30kTo50k', '{"우드윅 캔들","집들이 캔들"}', '타닥이는 소리가 나는 우드윅 캔들. 약 40시간 연소됩니다.',
   '공간 분위기를 바꾸는 선물로 잘 맞아요.', true, 16),
  ('candle_02', '센트그램', '리드 디퓨저 200ml + 리필', 'candle', '디퓨저',
   46000, null, null, null, null,
   '{"scent","home"}', '{"housewarming","thanks","anniversary"}', '{"family","acquaintance","partner"}', null, '{"thirties","fortiesPlus"}',
   'from30kTo50k', '{"디퓨저 선물세트","집들이 디퓨저"}', '현관이나 거실에 두는 리드 디퓨저 본품과 리필 구성입니다.',
   '오래 쓰면서 선물다운 특별함이 남아요.', true, 17),
  ('candle_03', '무드셀렉트', '티라이트 캔들 24p 틴', 'candle', '캔들',
   19000, null, null, null, null,
   '{"scent","home"}', '{"housewarming","thanks","holiday"}', '{"friend","acquaintance","colleague"}', null, '{"twenties","thirties"}',
   'from10kTo30k', '{"티라이트 캔들","무향 캔들"}', '무향 티라이트 24개 구성. 캔들 홀더와 함께 쓰기 좋습니다.',
   '향 부담 없이 분위기만 더할 수 있어요.', true, 18),
  ('stationery_01', '노트하우스', '양장 노트 & 펜 세트', 'stationery', '노트',
   27000, 32000, 16, null, null,
   '{"office","practical"}', '{"promotion","support","thanks","birthday"}', '{"colleague","friend","manager"}', null, '{"teens","twenties","thirties"}',
   'from10kTo30k', '{"노트 선물세트","승진 선물 문구"}', '180도로 펼쳐지는 양장 노트와 젤 펜을 함께 담았습니다.',
   '새로 시작하는 자리에 어울리는 선물이에요.', true, 19),
  ('stationery_02', '페이퍼링', '주간 플래너 12개월', 'stationery', '플래너',
   21000, null, null, null, null,
   '{"office","practical"}', '{"promotion","support","holiday"}', '{"colleague","friend"}', null, '{"twenties","thirties"}',
   'from10kTo30k', '{"플래너 선물","다이어리 선물"}', '날짜가 비어 있어 언제 시작해도 되는 12개월 주간 플래너입니다.',
   '시작을 응원하는 의미를 담기 좋아요.', true, 20),
  ('stationery_03', '노트하우스', '만년필 입문 세트', 'stationery', '필기구',
   52000, null, null, null, null,
   '{"office","practical"}', '{"promotion","anniversary","thanks"}', '{"manager","colleague","family"}', null, '{"thirties","fortiesPlus"}',
   'from50kTo100k', '{"만년필 선물","승진 축하 선물"}', 'EF촉 만년필과 카트리지, 컨버터를 담은 입문용 구성입니다.',
   '격식 있는 자리에 어울리는 선물이에요.', true, 21),
  ('desk_01', '스테이블', '월넛 모니터 스탠드', 'desk', '데스크 정리',
   64000, 78000, 18, null, null,
   '{"office","practical"}', '{"promotion","housewarming","support"}', '{"colleague","manager","friend"}', null, '{"twenties","thirties","fortiesPlus"}',
   'from50kTo100k', '{"모니터 받침대","데스크 정리 선물"}', '원목 무늬 모니터 받침대. 아래 공간에 키보드를 넣어 정리할 수 있습니다.',
   '매일 쓰는 자리에 남는 실용적인 선물이에요.', true, 22),
  ('desk_02', '스테이블', '알루미늄 노트북 스탠드', 'desk', '데스크 정리',
   39000, null, null, null, null,
   '{"office","practical","digital"}', '{"promotion","support","birthday"}', '{"colleague","friend"}', null, '{"twenties","thirties"}',
   'from30kTo50k', '{"노트북 거치대","재택 근무 선물"}', '각도 조절이 되는 접이식 노트북 거치대입니다.',
   '자세를 편하게 바꿔주는 실용 선물이에요.', true, 23),
  ('desk_03', '터치우드', '데스크 정리 트레이', 'desk', '데스크 정리',
   24000, null, null, null, null,
   '{"office","practical","home"}', '{"promotion","housewarming","thanks"}', '{"colleague","manager","acquaintance"}', null, '{"thirties","fortiesPlus"}',
   'from10kTo30k', '{"데스크 트레이","책상 정리 선물"}', '펜, 카드, 이어폰을 나눠 담는 3칸 트레이입니다.',
   '자리를 정돈해 주는 부담 없는 선물이에요.', true, 24),
  ('homewear_01', '코지룸', '워싱 코튼 홈웨어 세트', 'homewear', '잠옷',
   54000, 62000, 13, null, null,
   '{"home","sizing"}', '{"birthday","anniversary","holiday"}', '{"partner","family"}', null, '{"twenties","thirties","fortiesPlus"}',
   'from50kTo100k', '{"홈웨어 세트","잠옷 선물"}', '여러 번 빨아도 부드러운 워싱 코튼 상하의 세트입니다.',
   '집에서 쉬는 시간을 챙겨주는 선물이에요.', true, 25),
  ('homewear_02', '코지룸', '극세사 무릎 담요', 'homewear', '담요',
   26000, null, null, null, null,
   '{"home","practical"}', '{"thanks","support","holiday","housewarming"}', '{"colleague","family","friend"}', null, '{"twenties","thirties","fortiesPlus"}',
   'from10kTo30k', '{"무릎담요 선물","사무실 담요"}', '사무실 의자에 두고 쓰기 좋은 크기의 무릎 담요입니다.',
   '사이즈 걱정 없이 건넬 수 있어요.', true, 26),
  ('homewear_03', '하루살림', '호텔식 타월 4매 세트', 'homewear', '타월',
   42000, 49000, 14, null, null,
   '{"home","practical"}', '{"housewarming","thanks","holiday","birth"}', '{"family","acquaintance","colleague"}', null, '{"thirties","fortiesPlus"}',
   'from30kTo50k', '{"호텔 타월 세트","집들이 타월"}', '40수 면사로 짠 호텔식 타월 4매 구성입니다.',
   '소비가 빠른 생활용품이라 실패가 없어요.', true, 27),
  ('fashion_accessory_01', '무드셀렉트', '캐시미어 혼방 머플러', 'fashion_accessory', '머플러',
   72000, 89000, 19, null, null,
   '{"sizing"}', '{"birthday","anniversary","holiday"}', '{"partner","family","friend"}', null, '{"twenties","thirties","fortiesPlus"}',
   'from50kTo100k', '{"머플러 선물","겨울 선물"}', '캐시미어를 섞어 가볍고 따뜻한 머플러입니다.',
   '겨울 선물로 무게감이 있어요.', true, 28),
  ('fashion_accessory_02', '그린포켓', '미니멀 실버 체인 목걸이', 'fashion_accessory', '주얼리',
   59000, null, null, null, null,
   '{"strongTaste"}', '{"anniversary","birthday"}', '{"partner","friend"}', null, '{"twenties","thirties"}',
   'from50kTo100k', '{"실버 목걸이","기념일 주얼리"}', '얇은 체인에 작은 펜던트를 단 데일리 목걸이입니다.',
   '기념일에 오래 남는 선물이 돼요.', true, 29),
  ('fashion_accessory_03', '그린포켓', '가죽 키링 & 카드홀더', 'fashion_accessory', '키링',
   28000, 33000, 15, null, null,
   '{"practical"}', '{"promotion","thanks","birthday"}', '{"colleague","friend","acquaintance"}', null, '{"twenties","thirties"}',
   'from10kTo30k', '{"가죽 키링","카드홀더 선물"}', '소가죽 키링에 카드 한 장을 넣을 수 있는 홀더가 붙어 있습니다.',
   '가볍게 챙기기 좋은 실용 선물이에요.', true, 30),
  ('wallet_01', '그린포켓', '슬림 카드지갑', 'wallet', '카드지갑',
   45000, null, null, null, null,
   '{"practical"}', '{"promotion","birthday","thanks"}', '{"colleague","friend","partner"}', null, '{"twenties","thirties"}',
   'from30kTo50k', '{"카드지갑 선물","슬림 지갑"}', '카드 6장과 지폐를 넣는 얇은 가죽 카드지갑입니다.',
   '매일 들고 다니는 물건이라 오래 기억돼요.', true, 31),
  ('wallet_02', '무드셀렉트', '반지갑 · 이니셜 각인', 'wallet', '반지갑',
   89000, 105000, 15, null, null,
   '{"practical","strongTaste"}', '{"anniversary","promotion","birthday"}', '{"partner","family","manager"}', null, '{"thirties","fortiesPlus"}',
   'from50kTo100k', '{"이니셜 각인 지갑","반지갑 선물"}', '이니셜 각인을 넣을 수 있는 소가죽 반지갑입니다.',
   '특별한 날 의미를 더하기 좋아요.', true, 32),
  ('tumbler_01', '워터드롭', '진공 보온 텀블러 500ml', 'tumbler', '텀블러',
   38000, 44000, 14, null, null,
   '{"practical","home"}', '{"promotion","thanks","support","birthday"}', '{"colleague","friend","manager"}', null, '{"twenties","thirties","fortiesPlus"}',
   'from30kTo50k', '{"보온 텀블러","사무실 텀블러"}', '6시간 보온이 유지되는 스테인리스 텀블러입니다.',
   '사용 빈도가 높아 실패 확률이 낮아요.', true, 33),
  ('tumbler_02', '워터드롭', '가벼운 데일리 보틀 700ml', 'tumbler', '보틀',
   26000, null, null, null, null,
   '{"practical"}', '{"support","birthday","thanks"}', '{"friend","colleague"}', null, '{"teens","twenties","thirties"}',
   'from10kTo30k', '{"물병 선물","데일리 보틀"}', '한 손에 들어오는 가벼운 트라이탄 물병입니다.',
   '가격 부담 없이 챙기기 좋아요.', true, 34),
  ('tumbler_03', '블랑테이블', '더블월 유리컵 2P', 'tumbler', '유리컵',
   32000, null, null, null, null,
   '{"home","practical"}', '{"housewarming","thanks","anniversary"}', '{"family","acquaintance","partner"}', null, '{"thirties","fortiesPlus"}',
   'from30kTo50k', '{"유리컵 선물","집들이 컵"}', '이중 유리로 뜨거운 음료도 잡기 편한 컵 2개 구성입니다.',
   '집들이 선물로 실용적이에요.', true, 35),
  ('living_01', '하루살림', '실리콘 주방 도구 5종', 'living', '주방',
   34000, null, null, null, null,
   '{"home","practical"}', '{"housewarming","holiday","thanks"}', '{"family","acquaintance","friend"}', null, '{"thirties","fortiesPlus"}',
   'from30kTo50k', '{"주방도구 선물","집들이 주방"}', '열에 강한 실리콘 주걱과 집게 등 5종 구성입니다.',
   '새로 시작하는 살림에 바로 쓰여요.', true, 36),
  ('living_02', '라온홈', '무선 탁상 무드등', 'living', '조명',
   44000, 52000, 15, null, null,
   '{"home"}', '{"housewarming","birthday","anniversary"}', '{"partner","friend","family"}', null, '{"twenties","thirties"}',
   'from30kTo50k', '{"무드등 선물","탁상 조명"}', '3단계 밝기 조절이 되는 충전식 무드등입니다.',
   '공간 분위기를 바꾸는 선물이에요.', true, 37),
  ('living_03', '라온홈', '미니 가습기 · 저소음', 'living', '계절가전',
   49000, null, null, null, null,
   '{"home","digital","practical"}', '{"housewarming","support","birth"}', '{"family","colleague","friend"}', null, '{"twenties","thirties","fortiesPlus"}',
   'from30kTo50k', '{"미니 가습기","사무실 가습기"}', '책상 위에 두는 저소음 미니 가습기입니다.',
   '건조한 계절에 실용적으로 쓰여요.', true, 38),
  ('living_04', '하루살림', '다회용 장바구니 3종', 'living', '생활잡화',
   19000, null, null, null, null,
   '{"home","practical"}', '{"thanks","housewarming","holiday"}', '{"family","acquaintance","colleague"}', null, '{"thirties","fortiesPlus"}',
   'from10kTo30k', '{"장바구니 선물","에코백 선물"}', '작게 접히는 다회용 장바구니 3장 구성입니다.',
   '부담 없이 건네기 좋은 가격대예요.', true, 39),
  ('beauty_01', '온도', '립밤 & 립 스크럽 듀오', 'beauty', '립케어',
   24000, 29000, 17, null, null,
   '{"beauty","scent"}', '{"birthday","thanks","support"}', '{"friend","colleague"}', null, '{"teens","twenties","thirties"}',
   'from10kTo30k', '{"립밤 선물","립케어 세트"}', '건조한 계절에 쓰기 좋은 립 스크럽과 립밤 구성입니다.',
   '작지만 챙긴 느낌이 분명해요.', true, 40),
  ('beauty_02', '데일리핏', '수분 마스크팩 10매 박스', 'beauty', '스킨케어',
   22000, null, null, null, null,
   '{"beauty"}', '{"thanks","support","birthday","holiday"}', '{"friend","colleague","family"}', null, '{"teens","twenties","thirties"}',
   'from10kTo30k', '{"마스크팩 선물","수분팩 세트"}', '자극이 적은 수분 마스크팩 10매 구성입니다.',
   '가볍게 나눠 쓰기 좋은 선물이에요.', true, 41),
  ('beauty_03', '무드셀렉트', '헤어 & 바디 트래블 키트', 'beauty', '여행용',
   31000, 37000, 16, null, null,
   '{"beauty","scent","practical"}', '{"support","birthday","thanks"}', '{"friend","colleague","partner"}', null, '{"twenties","thirties"}',
   'from30kTo50k', '{"여행 키트 선물","트래블 세트"}', '출장이나 여행에 들고 가기 좋은 소용량 5종 키트입니다.',
   '이동이 잦은 사람에게 실용적이에요.', true, 42),
  ('hobby_01', '터치우드', '우드 퍼즐 · 미니 오르골', 'hobby', '소품',
   36000, null, null, null, null,
   '{"hobby","home"}', '{"birthday","anniversary","support"}', '{"partner","friend","family"}', null, '{"teens","twenties","thirties"}',
   'from30kTo50k', '{"우드퍼즐 선물","오르골 선물"}', '조립하면 멜로디가 흐르는 원목 오르골 키트입니다.',
   '만드는 과정까지 선물이 돼요.', true, 43),
  ('hobby_02', '포레스트리', '반려식물 · 스투키 화분', 'hobby', '식물',
   32000, null, null, null, null,
   '{"plant","home"}', '{"housewarming","promotion","thanks"}', '{"colleague","manager","friend","family"}', null, '{"twenties","thirties","fortiesPlus"}',
   'from30kTo50k', '{"집들이 화분","관리 쉬운 식물"}', '물을 자주 주지 않아도 되는 스투키와 도자 화분 구성입니다.',
   '축하 자리에서 존재감이 있어요.', true, 44),
  ('hobby_03', '포레스트리', '드라이플라워 미니 부케', 'hobby', '플라워',
   27000, 33000, 18, null, null,
   '{"plant","strongTaste"}', '{"anniversary","birthday","thanks"}', '{"partner","friend"}', null, '{"twenties","thirties"}',
   'from10kTo30k', '{"드라이플라워 선물","미니 부케"}', '시들지 않는 드라이플라워를 작게 묶은 부케입니다.',
   '꽃을 오래 두고 볼 수 있어요.', true, 45),
  ('hobby_04', '모먼트', '필름 카메라 감성 포토 프레임', 'hobby', '소품',
   29000, null, null, null, null,
   '{"hobby","home","strongTaste"}', '{"anniversary","birthday","housewarming"}', '{"partner","friend","family"}', null, '{"teens","twenties","thirties"}',
   'from10kTo30k', '{"포토 프레임 선물","기념일 액자"}', '사진 네 장을 나란히 끼우는 우드 프레임입니다.',
   '함께한 기억을 남기는 선물이에요.', true, 46)
on conflict (id) do update set
  brand_name = excluded.brand_name,
  product_name = excluded.product_name,
  category_id = excluded.category_id,
  sub_category = excluded.sub_category,
  price = excluded.price,
  original_price = excluded.original_price,
  discount_rate = excluded.discount_rate,
  tags = excluded.tags,
  occasions = excluded.occasions,
  recipient_types = excluded.recipient_types,
  age_range = excluded.age_range,
  price_range = excluded.price_range,
  recommendation_keywords = excluded.recommendation_keywords,
  description = excluded.description,
  recommendation_reason = excluded.recommendation_reason,
  sort_order = excluded.sort_order,
  is_active = true;

-- product_categories ----------------------------------------
insert into public.product_categories (product_id, category_id, is_primary, sort_order) values
  ('perfume_01', 'perfume', true, 1),
  ('perfume_02', 'perfume', true, 2),
  ('perfume_03', 'perfume', true, 3),
  ('hand_care_01', 'hand_care', true, 4),
  ('hand_care_02', 'hand_care', true, 5),
  ('hand_care_03', 'hand_care', true, 6),
  ('body_care_01', 'body_care', true, 7),
  ('body_care_02', 'body_care', true, 8),
  ('body_care_03', 'body_care', true, 9),
  ('tea_coffee_01', 'tea_coffee', true, 10),
  ('tea_coffee_02', 'tea_coffee', true, 11),
  ('tea_coffee_03', 'tea_coffee', true, 12),
  ('dessert_01', 'dessert', true, 13),
  ('dessert_02', 'dessert', true, 14),
  ('dessert_03', 'dessert', true, 15),
  ('candle_01', 'candle', true, 16),
  ('candle_02', 'candle', true, 17),
  ('candle_03', 'candle', true, 18),
  ('stationery_01', 'stationery', true, 19),
  ('stationery_02', 'stationery', true, 20),
  ('stationery_03', 'stationery', true, 21),
  ('desk_01', 'desk', true, 22),
  ('desk_02', 'desk', true, 23),
  ('desk_03', 'desk', true, 24),
  ('homewear_01', 'homewear', true, 25),
  ('homewear_02', 'homewear', true, 26),
  ('homewear_03', 'homewear', true, 27),
  ('fashion_accessory_01', 'fashion_accessory', true, 28),
  ('fashion_accessory_02', 'fashion_accessory', true, 29),
  ('fashion_accessory_03', 'fashion_accessory', true, 30),
  ('wallet_01', 'wallet', true, 31),
  ('wallet_02', 'wallet', true, 32),
  ('tumbler_01', 'tumbler', true, 33),
  ('tumbler_02', 'tumbler', true, 34),
  ('tumbler_03', 'tumbler', true, 35),
  ('living_01', 'living', true, 36),
  ('living_02', 'living', true, 37),
  ('living_03', 'living', true, 38),
  ('living_04', 'living', true, 39),
  ('beauty_01', 'beauty', true, 40),
  ('beauty_02', 'beauty', true, 41),
  ('beauty_03', 'beauty', true, 42),
  ('hobby_01', 'hobby', true, 43),
  ('hobby_02', 'hobby', true, 44),
  ('hobby_03', 'hobby', true, 45),
  ('hobby_04', 'hobby', true, 46)
on conflict (product_id, category_id) do update set
  is_primary = excluded.is_primary,
  sort_order = excluded.sort_order;

-- collections -----------------------------------------------
insert into public.collections (id, title, subtitle, sort_order) values
  ('spotlight', '요즘 눈여겨볼 선물', '지금 할인 중인 데모 상품', 1),
  ('giftmap_picks', 'Giftmap 추천 상품', '상황을 가리지 않고 무난한 선택', 2),
  ('under_30k', '부담 없이 마음을 전하기 좋은 선물', '가볍게 건네기 좋은 가격대', 3)
on conflict (id) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  sort_order = excluded.sort_order,
  is_active = true;

-- collection_products --------------------------------------
insert into public.collection_products (collection_id, product_id, sort_order) values
  ('spotlight', 'perfume_01', 1),
  ('spotlight', 'perfume_03', 2),
  ('spotlight', 'hand_care_01', 3),
  ('spotlight', 'body_care_02', 4),
  ('spotlight', 'tea_coffee_01', 5),
  ('spotlight', 'tea_coffee_03', 6),
  ('spotlight', 'dessert_02', 7),
  ('spotlight', 'candle_01', 8),
  ('spotlight', 'stationery_01', 9),
  ('spotlight', 'desk_01', 10),
  ('spotlight', 'homewear_01', 11),
  ('spotlight', 'homewear_03', 12),
  ('spotlight', 'fashion_accessory_01', 13),
  ('spotlight', 'fashion_accessory_03', 14),
  ('spotlight', 'wallet_02', 15),
  ('spotlight', 'tumbler_01', 16),
  ('spotlight', 'living_02', 17),
  ('spotlight', 'beauty_01', 18),
  ('spotlight', 'beauty_03', 19),
  ('spotlight', 'hobby_03', 20),
  ('giftmap_picks', 'perfume_02', 1),
  ('giftmap_picks', 'perfume_03', 2),
  ('giftmap_picks', 'hand_care_01', 3),
  ('giftmap_picks', 'hand_care_02', 4),
  ('giftmap_picks', 'body_care_01', 5),
  ('giftmap_picks', 'body_care_02', 6),
  ('giftmap_picks', 'tea_coffee_01', 7),
  ('giftmap_picks', 'tea_coffee_02', 8),
  ('giftmap_picks', 'tea_coffee_03', 9),
  ('giftmap_picks', 'dessert_01', 10),
  ('giftmap_picks', 'dessert_02', 11),
  ('giftmap_picks', 'dessert_03', 12),
  ('giftmap_picks', 'candle_01', 13),
  ('giftmap_picks', 'candle_02', 14),
  ('giftmap_picks', 'candle_03', 15),
  ('giftmap_picks', 'stationery_01', 16),
  ('giftmap_picks', 'stationery_02', 17),
  ('giftmap_picks', 'stationery_03', 18),
  ('giftmap_picks', 'desk_01', 19),
  ('giftmap_picks', 'desk_02', 20),
  ('giftmap_picks', 'desk_03', 21),
  ('giftmap_picks', 'homewear_01', 22),
  ('giftmap_picks', 'homewear_02', 23),
  ('giftmap_picks', 'homewear_03', 24),
  ('giftmap_picks', 'fashion_accessory_01', 25),
  ('giftmap_picks', 'fashion_accessory_03', 26),
  ('giftmap_picks', 'wallet_01', 27),
  ('giftmap_picks', 'wallet_02', 28),
  ('giftmap_picks', 'tumbler_01', 29),
  ('giftmap_picks', 'tumbler_02', 30),
  ('giftmap_picks', 'tumbler_03', 31),
  ('giftmap_picks', 'living_01', 32),
  ('giftmap_picks', 'living_02', 33),
  ('giftmap_picks', 'living_03', 34),
  ('giftmap_picks', 'living_04', 35),
  ('giftmap_picks', 'beauty_01', 36),
  ('giftmap_picks', 'beauty_02', 37),
  ('giftmap_picks', 'beauty_03', 38),
  ('giftmap_picks', 'hobby_01', 39),
  ('giftmap_picks', 'hobby_02', 40),
  ('giftmap_picks', 'hobby_03', 41),
  ('giftmap_picks', 'hobby_04', 42),
  ('under_30k', 'perfume_03', 1),
  ('under_30k', 'hand_care_02', 2),
  ('under_30k', 'hand_care_03', 3),
  ('under_30k', 'body_care_01', 4),
  ('under_30k', 'tea_coffee_01', 5),
  ('under_30k', 'dessert_01', 6),
  ('under_30k', 'dessert_03', 7),
  ('under_30k', 'candle_03', 8),
  ('under_30k', 'stationery_01', 9),
  ('under_30k', 'stationery_02', 10),
  ('under_30k', 'desk_03', 11),
  ('under_30k', 'homewear_02', 12),
  ('under_30k', 'fashion_accessory_03', 13),
  ('under_30k', 'tumbler_02', 14),
  ('under_30k', 'living_04', 15),
  ('under_30k', 'beauty_01', 16),
  ('under_30k', 'beauty_02', 17),
  ('under_30k', 'hobby_03', 18),
  ('under_30k', 'hobby_04', 19)
on conflict (collection_id, product_id) do update set
  sort_order = excluded.sort_order;

-- search_suggestions ---------------------------------------
insert into public.search_suggestions (id, keyword, sort_order) values
  ('suggestion_1', '집들이 선물', 1),
  ('suggestion_2', '핸드크림', 2),
  ('suggestion_3', '디퓨저', 3),
  ('suggestion_4', '텀블러', 4),
  ('suggestion_5', '차 선물세트', 5),
  ('suggestion_6', '데스크 정리', 6)
on conflict (id) do update set
  keyword = excluded.keyword,
  sort_order = excluded.sort_order,
  is_active = true;

commit;

-- 확인용 조회
-- select count(*) from public.products where is_active;
-- select count(*) from public.categories where is_active;
